### ISSUE TITLE
Sync Up AK Harbor Seal Components

### ISSUE THREAD

**Issue by jmlondon** [staciekoslovsky-noaa/PEP_Dashboard#16]
I'm proposing the following AK Harbor Seal Components for 2023:
- Aerial Surveys of Harbor Seals in Alaska (lead: London)
- Abundance & Trend Analysis for Harbor Seal Stocks (lead: Boveng)
- Harbor Seal Reporting (lead: London)*
- Vessel Disturbance of Glacial Harbor Seals (lead: Jansen)
- Scientific Assessment & Stakeholder Support (lead: Richmond)
- AK Harbor Seals 3.0 (lead: London)*
- Aleutian Islands Harbor Seal Ecology (lead: Dahle)

* new components for 2023

See [AK Harbor Seal Program Overview - Components & Projects](https://docs.google.com/document/d/1R54HOXmwPIJwIdUS29yDXOjGkTMAEuOZRlcYdov97U0/edit#) for more details

**Comment by staciekoslovsky-noaa** [comment]
The new components have been added to the DB
